// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFadp37Na_68vNZPlqAaPhbPdeaebpg4A',
    appId: '1:154378923582:web:dadafe825c9b7840426b6f',
    messagingSenderId: '154378923582',
    projectId: 'ifrsquiz',
    authDomain: 'ifrsquiz.firebaseapp.com',
    storageBucket: 'ifrsquiz.appspot.com',
    measurementId: 'G-S0SZEGE3CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGidQMc09z8HqEF8f1NU9AGUwKlg8U3o',
    appId: '1:154378923582:android:212bf193b2760663426b6f',
    messagingSenderId: '154378923582',
    projectId: 'ifrsquiz',
    storageBucket: 'ifrsquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0muAvIYQu_FSTycSdyEmGJ2X3PkVPNU',
    appId: '1:154378923582:ios:f0c033226a7bb3a9426b6f',
    messagingSenderId: '154378923582',
    projectId: 'ifrsquiz',
    storageBucket: 'ifrsquiz.appspot.com',
    androidClientId: '154378923582-k5qr3s0f22jj6badjkfmv5mnb1r8u7lp.apps.googleusercontent.com',
    iosClientId: '154378923582-jus6u86joikrafapp63dte109cr61un6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifrsquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0muAvIYQu_FSTycSdyEmGJ2X3PkVPNU',
    appId: '1:154378923582:ios:4071296fbab1889b426b6f',
    messagingSenderId: '154378923582',
    projectId: 'ifrsquiz',
    storageBucket: 'ifrsquiz.appspot.com',
    androidClientId: '154378923582-k5qr3s0f22jj6badjkfmv5mnb1r8u7lp.apps.googleusercontent.com',
    iosClientId: '154378923582-1bvf56b1etmigcgrgdiq2r014sf4b0t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifrsquiz.RunnerTests',
  );
}
